<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>RW1.6;RW1.6Unstable</Configurations>
    <Configuration Condition=" '$(Configuration)' == '' ">RW1.6</Configuration>
    <AssemblyName>DoorsExpanded</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <NoStdLib>true</NoStdLib>
    <LangVersion>10</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\..\About\Version.txt"))</Version>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Always using "Release" build -->
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <Choose>
    <When Condition=" '$(Configuration)' == 'RW1.6' ">
      <PropertyGroup>
        <OutputPath>..\1.6\Assemblies\</OutputPath>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
      </ItemGroup>
    </When>
    <When Condition=" '$(Configuration)' == 'RW1.6Unstable' ">
      <PropertyGroup>
        <OutputPath>..\1.6\Assemblies\</OutputPath>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
      </ItemGroup>
    </When>
  </Choose>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.2.*" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Building_Door_Reference\Building_Door.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Building_Door_Reference\Building_Door.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\**\*" Exclude="..\.git\**\*;..\Source\**\*" LinkBase="!ModFolder" />
  </ItemGroup>
</Project>
