<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>RW1.6;RW1.6Unstable</Configurations>
    <Configuration Condition=" '$(Configuration)' == '' ">RW1.6</Configuration>
    <AssemblyName>DoorsExpanded</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <NoStdLib>true</NoStdLib>
    <LangVersion>10</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\..\About\Version.txt"))</Version>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Always using "Release" build -->
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <!-- Package references are defined in Directory.Build.props to avoid duplicates -->
  <ItemGroup>
    <Content Include="..\**\*" Exclude="..\.git\**\*;..\Source\**\*" LinkBase="!ModFolder" />
  </ItemGroup>
</Project>
